robot_cameras:
  floor_robot_camera: 
    active: false
    type: rgb
  
  ceiling_robot_camera: 
    active: false
    type: rgbd

static_sensors:
  right_bins_camera:
    type: advanced_logical_camera
    visualize_fov: false
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    visualize_fov: false
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    visualize_fov: false
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    visualize_fov: false
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]

  conveyor_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-0.573, 4.4, 1.8]
      rpy: [pi/2, pi/2, 0]
  
  conveyor_breakbeam:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.352, 3.65, 0.88]
      rpy: [0, 0, pi]

  conveyor_breakbeam2:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.352, 1.0, 0.88]
      rpy: [0, 0.0, pi]
    
  conveyor_breakbeam3:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.352, 0.195, 0.88]
      rpy: [0, 0.0, pi]
  

